name: android
on: push
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    
    - name: Install Qt dependency packages
      run: |
        sudo apt-get update
        sudo apt-get --no-install-recommends --yes install \
          build-essential \
          g++ \
          cmake \
          ninja-build \
          libgl1-mesa-dev \
          libxkbcommon-dev \
          libxkbcommon-x11-dev
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Install Android SDK command line tools
      run: |
        mkdir -p ${ANDROID_HOME}/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip -d ${ANDROID_HOME}/cmdline-tools
        mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest
        rm commandlinetools-linux-9477386_latest.zip
        echo "y" | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses
    
    - name: Install Android SDK and NDK
      run: |
        ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;33.0.0" "ndk;25.1.8937393"
        echo "ANDROID_NDK_ROOT=${ANDROID_HOME}/ndk/25.1.8937393" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=${ANDROID_HOME}/ndk/25.1.8937393" >> $GITHUB_ENV
        
    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
    
    - name: Install QtForAndroid
      run: |
        pip install aqt
        aqt install-qt linux android 6.5.0 android_armv7
        export QT_ANDROID=${QT_ROOT}/6.5.0/android_armv7
        echo "QT_ANDROID=${QT_ROOT}/6.5.0/android_armv7" >> $GITHUB_ENV
        
    - name: Generate keystore
      run: |
        mkdir -p android-build
        keytool -genkey -v -keystore android-build/android-release-key.keystore \
        -alias alias_name -keyalg RSA -keysize 2048 -validity 10000 \
        -dname "CN=Datacorn, OU=Organization, O=Company, L=City, S=State, C=Country" \
        -storepass password -keypass password
    
    - name: Create AndroidManifest.xml if not exists
      run: |
        if [ ! -f "android/AndroidManifest.xml" ]; then
          mkdir -p android
          cat > android/AndroidManifest.xml << EOL
        <?xml version="1.0"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android" 
                  package="com.example.datacorn" 
                  android:versionName="1.0" 
                  android:versionCode="1" 
                  android:installLocation="auto">
            <application android:name="org.qtproject.qt.android.bindings.QtApplication" 
                         android:label="Datacorn" 
                         android:icon="@drawable/icon">
                <activity android:name="org.qtproject.qt.android.bindings.QtActivity" 
                          android:label="Datacorn" 
                          android:screenOrientation="unspecified" 
                          android:configChanges="orientation|uiMode|screenLayout|screenSize|smallestScreenSize|layoutDirection|locale|fontScale|keyboard|keyboardHidden|navigation|mcc|mnc|density"
                          android:exported="true">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN"/>
                        <category android:name="android.intent.category.LAUNCHER"/>
                    </intent-filter>
                    <meta-data android:name="android.app.lib_name" android:value="Datacorn"/>
                    <meta-data android:name="android.app.arguments" android:value=""/>
                    <meta-data android:name="android.app.extract_android_style" android:value="minimal"/>
                </activity>
            </application>
            <supports-screens android:largeScreens="true" 
                              android:normalScreens="true" 
                              android:anyDensity="true" 
                              android:smallScreens="true"/>
            <uses-permission android:name="android.permission.INTERNET"/>
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
        </manifest>
        EOL
        fi
    
    - name: Modify .pro file for Android
      run: |
        # Create Android-specific section in .pro file if it doesn't exist
        if ! grep -q "android {" Datacorn.pro; then
          cat >> Datacorn.pro << EOL
        
        android {
            QT += androidextras
            ANDROID_PACKAGE_SOURCE_DIR = $$PWD/android
            ANDROID_ABIS = armeabi-v7a arm64-v8a x86 x86_64
        }
        EOL
        fi
    
    - name: Debug Qt environment
      run: |
        echo "Qt location: $Qt6_DIR"
        echo "Android Qt location: $QT_ANDROID"
        ls -la $Qt6_DIR/bin
        ls -la $QT_ANDROID/bin || echo "QT_ANDROID bin directory not found"
    
    - name: Build for Android
      run: |
        mkdir -p build-android && cd build-android
        
        # Use either Qt6_DIR/bin/qmake or the direct path based on QT_ROOT
        QMAKE_PATH="$Qt6_DIR/bin/qmake"
        if [ ! -f "$QMAKE_PATH" ]; then
          QMAKE_PATH="$QT_ROOT/6.5.0/android_armv7/bin/qmake"
        fi
        
        echo "Using qmake at: $QMAKE_PATH"
        $QMAKE_PATH PREFIX=/usr ../Datacorn.pro \
          "CONFIG+=release" \
          "CONFIG+=qtquickcompiler"
          
        make -j$(nproc)
        
        # Create APK
        make INSTALL_ROOT=android-build install
        
        # Find androiddeployqt
        ANDROIDDEPLOYQT_PATH="$Qt6_DIR/bin/androiddeployqt"
        if [ ! -f "$ANDROIDDEPLOYQT_PATH" ]; then
          ANDROIDDEPLOYQT_PATH="$QT_ROOT/6.5.0/android_armv7/bin/androiddeployqt"
        fi
        
        echo "Using androiddeployqt at: $ANDROIDDEPLOYQT_PATH"
        $ANDROIDDEPLOYQT_PATH \
          --input android-libDatacorn.so-deployment-settings.json \
          --output android-build \
          --android-platform android-33 \
          --jdk $JAVA_HOME \
          --gradle \
          --release \
          --sign ../android-build/android-release-key.keystore alias_name \
          --storepass password \
          --keypass password
    
    - name: Setup directory with artifacts
      shell: bash
      run: |
        export RDIR=Datacorn-Android
        mkdir -p $RDIR
        
        # Find the APK in different possible locations
        if [ -f "build-android/android-build/build/outputs/apk/release/android-build-release-signed.apk" ]; then
          cp build-android/android-build/build/outputs/apk/release/android-build-release-signed.apk $RDIR/Datacorn.apk
        elif [ -f "build-android/android-build/build/outputs/apk/debug/android-build-debug.apk" ]; then
          cp build-android/android-build/build/outputs/apk/debug/android-build-debug.apk $RDIR/Datacorn.apk
        else
          echo "APK not found. Searching for it..."
          find build-android/ -name "*.apk" -exec cp {} $RDIR/Datacorn.apk \;
        fi
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Datacorn-Android
        path: Datacorn-Android/
    
    - name: Release
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: svenstaro/upload-release-action@v2
      with:
        overwrite: true
        asset_name: datacorn-android
        prerelease: true
        tag: |
          latest
        file: |
          Datacorn-Android/Datacorn.apk
