name: macOS-build
on: push

jobs:
  macos-qt5:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          if [ ! -d "/usr/local/Homebrew" ]; then
            arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          fi
          arch -x86_64 /usr/local/bin/brew update
          arch -x86_64 /usr/local/bin/brew install qt@5
          echo "/usr/local/opt/qt@5/bin" >> $GITHUB_PATH

      - name: Qmake build
        run: |
          mkdir build && cd build
          arch -x86_64 /usr/bin/env QMAKE_APPLE_DEVICE_ARCHS=x86_64 /usr/local/opt/qt@5/bin/qmake -o Makefile "CONFIG+=x86_64" ../Datacorn.pro
          arch -x86_64 make release -j3

      - name: Bundle Qt5 frameworks into the app
        run: |
          arch -x86_64 macdeployqt build/binary/Datacorn.app

      - name: Setup directory with artifacts
        shell: bash
        run: |
          export RDIR=Datacorn
          mkdir $RDIR
          cp -R build/binary/Datacorn.app $RDIR/
          hdiutil create -volname "Datacorn-Intel" -srcfolder $RDIR -ov -format UDZO Datacorn-intel.dmg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Datacorn-macos-intel
          path: Datacorn/

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: Datacorn-macos-intel-dmg
          path: Datacorn-intel.dmg
